spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1000MB
server:
  port: 8088
  servlet:
    context-path: /file
swagger:
  enable: true
